### PR TITLE
add interface to build npy_array_list objects from C

### PR DESCRIPTION
**Pull request by alcubierre-drive**

### CODE REVIEW

**Comment by oysteijo** [comment]
Wow! My first real external PR! I will look at this when I come home!

fre. 20. sep. 2024 kl. 13:39 skrev Lennart Klebl ***@***.***>:

**Review by oysteijo — COMMENTED** [review]
It looks like `npy_array_alloc()` take a deep copy of an array. Maybe it is better to name it `npy_array_deepcopy()` ?

In my work I usually have huge arrays - there should be some check on the on the allocated memory.

**Comment by alcubierre-drive** [comment]
That makes a lot of sense. Changed it :)

**Comment by oysteijo** [comment]
I see nothing wrong! Merging!

**Comment by oysteijo** [comment]
Thanks a lot Lennart!

I think actually you are touching into the problem in #14. The user can have arrays where they do not "own" the items of the array_list. If you can think of somtheing better/simpler, I would love to hear ideas.

-Øystein

**Comment by alcubierre-drive** [comment]
How about a public and a private data pointer, where the private one is left as NULL in case the array doesn't own the data?

**Comment by oysteijo** [comment]
Hmmmm... Well... Sounds a bit like adding complexity. Then we should also
have a function/macro that returns the right pointer when requested.

**Pull request merged**
