### PR TITLE
Shallow copy of npy_array_t

### PR DESCRIPTION
**Pull request by alcubierre-drive**
Following the discussion in #30, I implemented my suggestion of having a private data member that is NULL in case an npy_array_t* object doesn't own its data. If you think the interface is getting too cluttered by this I would be very happy to discuss other approaches.

### CODE REVIEW

**Comment by oysteijo** [comment]
Yes! Yes! Yes! This makes sense! Let me just test out a few things. Should we also have some tests in the CI for for this feature?

**Comment by oysteijo** [comment]
Yes! Please add a run of the 'copying` example in the .github/workflows/make_and_examples.yaml file.

**Comment by alcubierre-drive** [comment]
I added the example to CI, including another example that reads the created file and checks for correctnes of the data.

**Comment by oysteijo** [comment]
Merging this! Thanks a lot Lennart! I will even close #14 with this merge.

**Pull request merged**
